import type { Metadata } from "next";
import "./globals.css";
import {Inter as FontSans} from "next/font/google"
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/toaster";

export const fontSans = FontSans({
  subsets:["latin"],
  variable:"--font-sans"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
            <ThemeProvider
             attribute="class"
             defaultTheme="system"
             enableSystem
             disableTransitionOnChange
            >
              {children}
            <Toaster/>
            </ThemeProvider>
      </body>
    </html>
  );
}